;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        align-repeat
        comment-region
        dired-back-to-start-of-files
        dired-do-chgrp
        down-list
        ghc-save-buffer
        handle-switch-frame
        haskell-indentation-delete-backward-char
        hungry-delete-backward
        indent-for-tab-command
        indent-region
        kill-and-join-forward
        kill-visual-line
        mark-whole-buffer
        org-beginning-of-line
        org-kill-line
        org-self-insert-command
        phi-rectangle-kill-region
        phi-rectangle-next-line
        phi-rectangle-yank
        scroll-right
        smart-beginning-of-line
        smart-end-of-line
        sp--self-insert-command
        sp-backward-symbol
        sp-forward-sexp
        sp-remove-active-pair-overlay
        undo-tree-visualize
        upcase-region
        wdired-finish-edit
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        yaml-electric-dash-and-dot
        yank-and-indent
        yas-expand
        yas-next-field-or-maybe-expand
        ))

(setq mc/cmds-to-run-once
      '(
        align-current
        bc-set
        helm-M-x
        helm-find-files
        ido-switch-buffer
        markdown-exdent-or-delete
        phi-search
        save-buffers-kill-terminal
        select-window-2
        sp-add-to-next-sexp
        sp-add-to-previous-sexp
        ))
