;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        align-repeat
        down-list
        handle-switch-frame
        indent-for-tab-command
        indent-region
        kill-visual-line
        phi-rectangle-kill-region
        phi-rectangle-next-line
        phi-rectangle-yank
        scroll-right
        smart-beginning-of-line
        smart-end-of-line
        sp--self-insert-command
        sp-forward-sexp
        sp-remove-active-pair-overlay
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        yank-and-indent
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        align-current
        bc-set
        markdown-exdent-or-delete
        save-buffers-kill-terminal
        ))
