;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-visual-line
        scroll-right
        phi-rectangle-kill-region
        indent-for-tab-command
        indent-region
        phi-rectangle-next-line
        phi-rectangle-yank
        smart-beginning-of-line
        smart-end-of-line
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        align-current
        bc-set
        ))
